d_seq: 4
d_count: 1
d_model: 256
n_heads: 8
number_of_layers: 10
pmt_len: 3
all_cell_types: ["aortic_endothelial_cell", "vascular_smooth_muscle_cell"]
d_ff: 512
p_drop: 0.1
model_name: "base_model_v2_256d_8h_10l_2c"
