d_seq: 4
d_count: 1
d_model: 512
d_expr: 16840
d_cell_env: 64
d_species: 16
all_species: ["human", "macaque", "mouse"]
expr_dict_path: None #"/home/user/data3/rbase/translation_model/models/src/config/cell_expression_dict.pt"
n_heads: 16
number_of_layers: 12
d_ff: 1024
adaptive_dim: 8
gamma_scale: 0.5
p_drop: 0.1
model_name: "base_model_expr_512d_16h_12l_64env_8ad"
